### ISSUE TITLE
Beanstalkd is not running

### ISSUE THREAD

**Issue by Osub** [Fixhub/Fixhub#1]
#安装 php artisan app:install
`Beanstalkd is not running`

**Comment by phecho** [comment]
把beankstalkd服务进程启动起来。

**Comment by Osub** [comment]
Type [mysql]:
  [0] mysql
  [1] sqlite

循环出现，我没法选择也 @phecho

**Comment by phecho** [comment]
请尝试使用laravel标准安装步骤试试看。

**Comment by Osub** [comment]
安装成功了@phecho
