### ISSUE TITLE
添加ssh key的时候，如果手动输入，会报错

### ISSUE THREAD

**Issue by shuipf** [Fixhub/Fixhub#101]
![image](https://user-images.githubusercontent.com/2285144/31604772-f04e2040-b229-11e7-92d4-0afe57afaf41.png)
这个是个小问题~~状态没及时更新。

![image](https://user-images.githubusercontent.com/2285144/31604798-088f463e-b22a-11e7-8fac-8cf09e09065e.png)
添加ssh key的时候，如果手动输入，会报这个错

**Comment by lianguan** [comment]
已修复。顺便提一下，你粘贴的内容不是私钥。
