### ISSUE TITLE
建议还是保留是否在该服务器部署代码的选项

### ISSUE THREAD

**Issue by shuipf** [Fixhub/Fixhub#104]

**Comment by lianguan** [comment]
“是否启用”、“是否在该服务器部署代码”和“部署时忽略该服务器”含义相同

**Comment by shuipf** [comment]
现在就一个 “是否启用”，如果不勾选，能执行对应脚本么？

**Comment by lianguan** [comment]
不能。之前的“是否在该服务器部署代码”也不能。执行对应脚本需要部署代码，有发布目录才可以。
