### ISSUE TITLE
操作不来, 可以提供一个操作文档吗？

### ISSUE THREAD

**Issue by tiandaye** [Fixhub/Fixhub#110]
我想知道为什么我填写私钥说我私钥有问题，不填写私钥如何知道我要部署到那台服务器!

**Comment by lianguan** [comment]
1、不填写私钥，系统会自动生成。
2、编辑项目的时候选择该私钥
3、进入项目详情页，右上脚有个“部署秘钥”，查看里面的内容，上面有帮助提示

**Comment by tiandaye** [comment]
3q

**Comment by tiandaye** [comment]
您说的 "部署秘钥" 指的是 "SSH秘钥" 按钮？

**Comment by lianguan** [comment]
对
