### ISSUE TITLE
ssh用户只能是root吗？

### ISSUE THREAD

**Issue by tiandaye** [Fixhub/Fixhub#113]
我用其他用户，ssh测试通，上线的时候报了 `Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).` 错误。

**Comment by lianguan** [comment]
不限定用户的，最好不要也不应该使用root。这个报错看起来像是ssh public key没有添加正确。

**Comment by tiandaye** [comment]
我好像要在 `root/.ssh` 里面和 用户名下的 `.ssh` 下面的 `authorized_keys` 都需要添加自动生成的公钥，还要设置相应的权限， 才解决的。
