### ISSUE TITLE
github私库上线失败

### ISSUE THREAD

**Issue by tiandaye** [Fixhub/Fixhub#117]
我在某个组织下面, 新建了一个私人仓库，我将生成的 `部署秘钥` 添加到 `Git` 仓库的 `Deploy Keys`。但是上线失败。

**Comment by lianguan** [comment]
有什么提示信息么？我没有github私有仓库的，暂时没法测试。我们团队内部与自己搭建的gitlab集成，私有项目没有问题。

**Comment by tiandaye** [comment]
我现在将 `git` 的 `url` 改为 `https://账号:密码@github.com` 形式
