### ISSUE TITLE
上线单前端显示有点问题。。

### ISSUE THREAD

**Issue by SimonFuu** [Fixhub/Fixhub#142]
浏览器：Chrome Version 61.0.3163.100 (Official Build) (64-bit) on Mac OS 10.12
其他分支下拉框展示不全，需要拖动水平方向滚动条。。。
![bug](https://user-images.githubusercontent.com/18401434/32031963-1ffac35a-b9ca-11e7-8734-b289eff7f3a3.png)

**Comment by lianguan** [comment]
已修复
