### ISSUE TITLE
Redis is not running

### ISSUE THREAD

**Issue by ttyob** [Fixhub/Fixhub#171]
报以下错误，但是我单独用php文件链接redis，是成功的

The compiled services & packages files have been removed.
Cache cleared successfully.
Route cache cleared!
Configuration cache cleared!
Compiled views cleared!

***********************
  Welcome to Fixhub  
***********************

Redis is not running

                                                                               
 Fixhub cannot be installed. Please review the errors above before continuing.

**Comment by lianguan** [comment]
.env文件 REDIS_PASSWORD值是什么？

**Comment by ttyob** [comment]
REDIS_HOST=127.0.0.1
28
REDIS_PORT=6379
29
REDIS_DATABASE=0
30
REDIS_PASSWORD=

**Comment by lianguan** [comment]
REDIS_PASSWORD=null
试试

**Comment by ttyob** [comment]
解决了..谢谢

**Comment by ttyob** [comment]
socket启动不起来0.0

![image](https://user-images.githubusercontent.com/11970912/32529447-a8ad786a-c473-11e7-8d2b-3bcc26641fa5.png)

![image](https://user-images.githubusercontent.com/11970912/32529423-7b1c24b4-c473-11e7-9268-66e34c1c734e.png)
