### ISSUE TITLE
执行composer install -o --no-dev报错

### ISSUE THREAD

**Issue by rockmelodies** [Fixhub/Fixhub#184]
![image](https://user-images.githubusercontent.com/24653177/32770563-ba39aed4-c8e5-11e7-92c8-795aab911f09.png)

**Comment by lianguan** [comment]
请根据提示安装一下php的fileinfo扩展。

**Comment by rockmelodies** [comment]
![image](https://user-images.githubusercontent.com/24653177/32771873-d0d3c50e-c8e9-11e7-93d8-538bc3c4ebe9.png)

**Comment by rockmelodies** [comment]
是这样吗

**Comment by lianguan** [comment]
linux下启用.so，无需去掉.dll的注释
