### ISSUE TITLE
Websocket通信失败

### ISSUE THREAD

**Issue by crazyfd** [Fixhub/Fixhub#186]
界面提示Websocket通信失败 ， 这个是哪里配置的，文档好少。

**Comment by lianguan** [comment]
这个原因是你的web socket服务没有起来。
请看examples/nginx.conf和examples/supevisor.conf
需要更多技术支持，请加入：656868的qq群。
谢谢。

**Comment by stbui** [comment]
在使用docker运行时，需要指定端口
```
docker run -d -p 80:80 -p 9000:9000 piplin
```
