### ISSUE TITLE
安装成功后还是不能访问

### ISSUE THREAD

**Issue by rockmelodies** [Fixhub/Fixhub#188]
![image](https://user-images.githubusercontent.com/24653177/32868159-796a65e0-ca36-11e7-8dc6-cf4424edb27f.png)
![image](https://user-images.githubusercontent.com/24653177/32868186-83eb8350-ca36-11e7-9406-5979875e0a9b.png)
![image](https://user-images.githubusercontent.com/24653177/32868196-8d446cdc-ca36-11e7-9632-e4526fbbac77.png)

**Comment by lianguan** [comment]
把debug打开，看storage/logs下的错误信息
