### ISSUE TITLE
环境部署问题

### ISSUE THREAD

**Issue by rockmelodies** [Fixhub/Fixhub#197]
每次使用fixhub进行自动上线部署，老是在root/目录下部署，
我想在指定web目录下部署进行composer 
![image](https://user-images.githubusercontent.com/24653177/33012094-dd57fcf6-ce1a-11e7-91dd-fafb6d903a5c.png)

![image](https://user-images.githubusercontent.com/24653177/33011845-14212ab0-ce1a-11e7-9799-0efc6211ba29.png)

**Comment by lianguan** [comment]
这个在1.0分支下已经解决了。现在安装时候(第二阶段)之后默认的工作目录就是项目的新版本所在目录。
https://github.com/fixhub/fixhub/commit/db5ac328725c5b9264e32b52d0f4bdbabc92880f
