### ISSUE TITLE
安装过程中用户表数据填充错误

### ISSUE THREAD

**Issue by maliang** [Fixhub/Fixhub#38]
app:install 之后，报：

> PHP Fatal error:Class 'Faker\Factory' not found in /var/......./database/seeds/UserTableSeeder.php on line 21
> 
> [Symfony\Component\Debug\Exception\FatalErrorException]
> Class 'Faker\Factory' not found

错误

**Comment by lianguan** [comment]
![image](https://user-images.githubusercontent.com/15666864/30197080-151f804e-9498-11e7-92b4-144c23e9f014.png)
我刚才试了一下，没有复现你提到的问题。
