### ISSUE TITLE
demo 帐号登录需要认证码

### ISSUE THREAD

**Issue by almas-x** [Fixhub/Fixhub#42]
登录demo帐号时需要输入认证码，README中也没说明认证码，因此无法登录；

**Comment by yaoshanliang** [comment]
对的，求认证码

**Comment by 000luna000** [comment]
@almas1992 用Goolge 身份验证器 扫描以下二维码，可以获取认证码
![image](https://user-images.githubusercontent.com/22146497/27525424-68bf84d6-5a70-11e7-9bc9-6c78badcafe5.png)

**Comment by lianguan** [comment]
@saqing thx
