### ISSUE TITLE
安装完后还是没有办法登录

### ISSUE THREAD

**Issue by litao941** [Fixhub/Fixhub#47]
页面提示：
糟糕! 你输入的信息有误.
登录失败.

1. 使用UserTableSeeder.php 账号 demo 提示以上错误
    public function run()
    {
        DB::table('users')->delete();

        $faker = Faker\Factory::create('en_GB');

        User::create([
            'name'           => 'demo',
            'email'          => 'demo@fixhub.org',
            'nickname'       => 'Demo',
            'password'       => 'demo',
            'remember_token' => str_random(10),
        ]);

2. 数据库可以查看到 user 表中只有 admin，不知道加密
mysql> select * from users\G
*************************** 1. row ***************************
              id: 1
            name: Admin
           email: admin@example.com
        password: $2y$10$Cy2X96VUQiQmLqegk2yjDuvM96M4awFN15VHXHEAY1sq4qsk7Jv86
        nickname: Administrator
  remember_token: NULL
           level: 1
     email_token: NULL
          avatar: /img/avatar.png
        language: NULL
            skin: NULL
google2fa_secret: NULL
      created_at: 2017-08-27 00:08:20
      updated_at: 2017-08-27 00:08:20
      deleted_at: NULL
1 row in set (0.00 sec)

mysql>

**Comment by lianguan** [comment]
密码是：password 这几个字符。
