### ISSUE TITLE
rsync 大的压缩包就无法正确上传文件成功

### ISSUE THREAD

**Issue by xuqihua** [Fixhub/Fixhub#48]
文件已经传到服务器上，但是process一直抛出超时的exception

**Comment by lianguan** [comment]
能把你的部署步骤里的命令和相关日志贴上来么？

**Comment by xuqihua** [comment]
@lianguan  应该是网络问题导致的，跟我本机有关系。 暂时没找到原因，估计需要配置rsync的参数

local.ERROR: Illuminate\Queue\TimeoutException: A queue worker timed out while processing a job. in /fixhub/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:103
