### ISSUE TITLE
增加日志

### ISSUE THREAD

**Issue by zuozhehao** [Fixhub/Fixhub#52]
建议增加日志查看~方便查找失败原因

**Comment by phecho** [comment]
哪方面的日志？如果是上线部署的话，可以查看远程服务器的控制台输出。

**Comment by zuozhehao** [comment]
最近上线列表那边,如果有上线失败的，建议可以再后面查看是在哪个环节失败.比如是拉取代码失败，还是部署失败.这样方便排查

**Comment by phecho** [comment]
@zuozhehao 
 
不是这个？

![image](https://cloud.githubusercontent.com/assets/15666864/18249747/bcfce192-73b2-11e6-9e0c-2508214f1a14.png)

**Comment by zuozhehao** [comment]
这个是啥情况,反复一直发布。
![qq 20160906163026](https://cloud.githubusercontent.com/assets/4464252/18266892/487afec4-744f-11e6-977c-900e432ec355.png)

**Comment by phecho** [comment]
在队列里有任务堆积吧。

**Comment by zuozhehao** [comment]
堆积任务也不能重复发布吧?都同一个版本号.那这是bug?

**Comment by phecho** [comment]
@zuozhehao 

不算bug。不能当看commit好相同就认为是重复。commit和deployment本身没有必然联系。

可以多个deployment都基于一个commit做上线。

**Comment by zuozhehao** [comment]
@phecho 主要是我是测试阶段，就只有我自己一个角色
