### ISSUE TITLE
Readme in english?

### ISSUE THREAD

**Issue by viezel** [Fixhub/Fixhub#56]
Hi guys,

project looks interesting. Would it be possible to translate the readme into english?

**Comment by REBELinBLUE** [comment]
You could take a look at the original if you want an English version REBELinBLUE/deployer ;) Just stumbled across this, looks like an interesting fork....

**Comment by phecho** [comment]
@viezel

Yes，Fixhub itself based highly on the deployer Project. but it is not compatible with deployer.

Thanks @REBELinBLUE
