### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [Fixhub/Fixhub#62]
![image](https://user-images.githubusercontent.com/13285922/31043969-befd16cc-a58b-11e7-92a6-c0b5bd8d2ded.png)

**Comment by lianguan** [comment]
git clone的最新代码？执行下git reset --hard origin/1.0试试。

**Comment by ghost** [comment]
在线demo的试用

**Comment by lianguan** [comment]
哦。那可能是刚才更新的时候出现的，现在应该不会有了。
