### ISSUE TITLE
共享文件/目录

### ISSUE THREAD

**Issue by zuozhehao** [Fixhub/Fixhub#62]
共享文件/目录 里设置 /data/
初始化的时候 /shared/data 有这个目录.

第二次开始的时候data的内容 /shared/data/data 多了一级了.

data的软连接还是指向了 /shared/data/

**Comment by phecho** [comment]
去掉前面的/试试

**Comment by phecho** [comment]
![image](https://cloud.githubusercontent.com/assets/15666864/18269982/4a8e86b4-745d-11e6-8af5-d4424c1c4ac8.png)

仅供参考。

**Comment by zuozhehao** [comment]
不行，试过了
