### ISSUE TITLE
UI Suggestions

### ISSUE THREAD

**Issue by ghost** [Fixhub/Fixhub#63]
![image](https://user-images.githubusercontent.com/13285922/31044055-49fcf278-a58d-11e7-88f2-f93393475463.png)

I think this is more beautiful.

![image](https://user-images.githubusercontent.com/13285922/31044054-446deaa6-a58d-11e7-818d-51c2bc3b9b88.png)

**Comment by lianguan** [comment]
赞，能否发一个PR？

**Comment by lianguan** [comment]
已在 #68 中实现。
