### ISSUE TITLE
There are some problems in app:install step

### ISSUE THREAD

**Issue by jiangchangduo** [Fixhub/Fixhub#64]
By add admin user, the password is plaintext storage. So, can't login.

**Comment by lianguan** [comment]
是个bug。你先用seeder执行成功后的fixhub，fixhub登录。这个也是管理员。

**Comment by jiangchangduo** [comment]
我直接用md5后的编码更新数据库了.

**Comment by lianguan** [comment]
已在0.2.2版本中修复。
