### ISSUE TITLE
0.1.2问题依旧(重新安装)

### ISSUE THREAD

**Issue by zuozhehao** [Fixhub/Fixhub#66]
![qq 20160907154130](https://cloud.githubusercontent.com/assets/4464252/18303836/9d5abea8-7511-11e6-88fe-b58a57af2dda.png)

问题依旧

**Comment by phecho** [comment]
输对密码了么？
我刚尝试了一下没有问题。
![image](https://cloud.githubusercontent.com/assets/15666864/18306723/b25117a4-751f-11e6-8e43-d9bda08c52e8.png)
