### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by jbrooksuk** [Fixhub/Fixhub#67]
@phecho,

I want to start by saying that your project looks very nice! Also that we sincerely appreciate your work on Cachet. I always attribute a lot of Cachet's success to being open source and without contributions such as yours we'd not have garnered as much attention as we've had. Please note that I do not want to burn bridges with our contributors, but it's important that we set precedents for licensing issues and copying code.

Your codebase contains a lot code from both Cachet (and Deployer, @REBELinBlue?), whilst neglecting to keep the original licenses intact.

Cachet is licensed under BSD-3:

> Copyright (c) 2015-2016 Alt Three Services Limited.
> All rights reserved.
> 
> Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
> 
>    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
>
>    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
>
>    3. Neither the name of the Cachet nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
>
> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Some examples from Cachet:

- https://github.com/Fixhub/Fixhub/blob/9e930c5665f2d7776c6b44a4f8a24cf31a33d638/resources/assets/sass/modules/_variables.scss — https://github.com/CachetHQ/Cachet/blob/904cf6a7db4e3d03947ea6e7d2d585c6a5ad0f6b/resources/assets/sass/modules/_variables.scss
- https://github.com/Fixhub/Fixhub/blob/9e930c5665f2d7776c6b44a4f8a24cf31a33d638/app/Services/Settings/Cache.php — https://github.com/CachetHQ/Cachet/blob/904cf6a7db4e3d03947ea6e7d2d585c6a5ad0f6b/app/Settings/Cache.php
- https://github.com/Fixhub/Fixhub/blob/9e930c5665f2d7776c6b44a4f8a24cf31a33d638/app/Services/Settings/Repository.php — https://github.com/CachetHQ/Cachet/blob/904cf6a7db4e3d03947ea6e7d2d585c6a5ad0f6b/app/Settings/Repository.php
- https://github.com/Fixhub/Fixhub/blob/1.0/app/Providers/ConfigServiceProvider.php — https://github.com/CachetHQ/Cachet/blob/904cf6a7db4e3d03947ea6e7d2d585c6a5ad0f6b/app/Foundation/Providers/ConfigServiceProvider.php

There are more places, but I feel this at least proves my claims. Please restore the original copyrights and the license provided by Cachet.

**Comment by phecho** [comment]
@jbrooksuk Thank you for reminding me. I'll check them carefully.

In fact, this is a learning project for me, and I will pay more attention to what you have mentioned.
