### ISSUE TITLE
可以发一下 部署任务的脚本 demo

### ISSUE THREAD

**Issue by bitqiu** [Fixhub/Fixhub#74]
rt

**Comment by lianguan** [comment]
这是我们其中一个项目的部署步骤。
1、图1

![image](https://user-images.githubusercontent.com/15666864/31372897-72132f58-adca-11e7-826d-5a3983f20149.png)


2、图2

![image](https://user-images.githubusercontent.com/15666864/31373189-ad749658-adcb-11e7-8f33-b99b94f58b0a.png)

```shell
composer install --no-interaction --optimize-autoloader --prefer-dist --no-ansi --working-dir "{{ release_path }}"
```
3、图3
![image](https://user-images.githubusercontent.com/15666864/31372939-a9324280-adca-11e7-8920-15ff0d5638f5.png)

数据迁移
```shell
php {{ release_path }}/artisan migrate
```
缓存配置
```shell
php {{ release_path }}/artisan config:cache
```

路由缓存
```shell
php {{ release_path }}/artisan route:cache
```

希望对你有帮助。
