### ISSUE TITLE
配置好上线单，为什么一直是等待中？是哪里没有配置好么

### ISSUE THREAD

**Issue by shuipf** [Fixhub/Fixhub#78]

**Comment by lianguan** [comment]
改成debug模式，看一下日志输出。很可能是你的git没配置好。

**Comment by shuipf** [comment]
请问有相应使用手册么？不然一些问题，问你，怕你也麻烦。。。

**Comment by shuipf** [comment]
我现在中止了，然后感觉就卡在那里了

**Comment by shuipf** [comment]
我把项目删除了，然后就提示：HTTP/1.0 500 Internal Server Error Cache-Control: no-cache, private Date: Wed, 11 Oct 2017 08:19:58 GMT

囧·

**Comment by lianguan** [comment]
@shuipf 

已在 PR #81 中修复，谢谢反馈。
