### ISSUE TITLE
已经升级到最新版，GIT我也不知道如何才是配置对的，现在上线还是等待中

### ISSUE THREAD

**Issue by shuipf** [Fixhub/Fixhub#82]
这个要怎么排查问题出在哪？开发模式已经打开了。不知道去那里看调试信息

**Comment by lianguan** [comment]
看storage/logs/cli*.log

**Comment by shuipf** [comment]
[2017-10-12 08:47:34] production.ERROR: Could not get repository info - bash: 第 5 行:cd: /home/wwwroot/fixhub/storage/app/mirrors/git_gitee.com_ruijiekeji_d1xz.git: 没有那个文件或目录
 {"exception":"[object] (RuntimeException(code: 0): Could not get repository info - bash: 第 5 行:cd: /home/wwwroot/fixhub/storage/app/mirrors/git_gitee.com_ruijiekeji_d1xz.git: 没有那个文件或目录
 at /home/wwwroot/fixhub/app/Bus/Jobs/DeployProjectJob.php:187)

**Comment by shuipf** [comment]
这个我也不知道是啥意思~~有QQ交流群么？

**Comment by lianguan** [comment]
应该是git信息没配置成功。你采用的是git@gitee.com协议的，需要ssh key授权。换成https://gitee.com即可。

**Comment by shuipf** [comment]
这个获取git环节能跳过不？我这的情况，其实想要的，更多是 Bash脚本 的执行。目标机器上执行这些脚本来完成任务。
