### ISSUE TITLE
反馈一个Bug，部署模板那边的

### ISSUE THREAD

**Issue by shuipf** [Fixhub/Fixhub#83]
在“部署模板”那边新增一个模板后，点击这个模板，随便点击一个执行任务，不管是前置任务还是后置任务，点新增，直接有一个错误提示：
![image](https://user-images.githubusercontent.com/2285144/31474168-a0bff274-aebe-11e7-8b93-87b7b55a575c.png)
查看浏览器控制台输出，是js报错了
![image](https://user-images.githubusercontent.com/2285144/31474173-b22112b4-aebe-11e7-9d87-ce3afa6e46ca.png)

**Comment by lianguan** [comment]
Fixed
