### ISSUE TITLE
昨天到今天，都没用起来~~

### ISSUE THREAD

**Issue by shuipf** [Fixhub/Fixhub#86]
能否指导下？上线一直是等待中，也没任何其他提示~~

**Comment by lianguan** [comment]
方便给我ssh账号么？我上去帮你看看。

**Comment by shuipf** [comment]
xxx

**Comment by shuipf** [comment]
我重装了~~你看看需要我怎么配合

**Comment by shuipf** [comment]
xxx

**Comment by lianguan** [comment]
已经配成功了

![image](https://user-images.githubusercontent.com/15666864/31532589-cdb5c2c8-b020-11e7-929e-e9602c94a55b.png)

**Comment by shuipf** [comment]
能告诉我是什么问题么？

**Comment by lianguan** [comment]
可能是两个原因吧：
1、队列服务，我没仔细看，直接把queue driver改为sync
2、部署ssh keys，我没尝试登录你的目标服务器，直接改成localhost
