### ISSUE TITLE
建议:上线单详情

### ISSUE THREAD

**Issue by zuozhehao** [Fixhub/Fixhub#88]
查看`上线单详情`打开非常的慢(有时候会超时).建议查看上线单的时候异步加载信息.

**Comment by lianguan** [comment]
部署环境和服务器特别多？

**Comment by zuozhehao** [comment]
单机而已.项目文件比较多.

**Comment by zuozhehao** [comment]
![201710131510130](https://user-images.githubusercontent.com/4464252/31534230-a8c2b7fc-b028-11e7-831e-5177a34e4bb8.png)

**Comment by lianguan** [comment]
这个主页面不会加载项目文件啊。只会加载服务器列表信息。

**Comment by zuozhehao** [comment]
上线单少的时候无此问题,大几万上线单就会出现这个问题.
