### ISSUE TITLE
第三方服务调用以下链接，触发Fixhub进行自动化部署工作

### ISSUE THREAD

**Issue by shuipf** [Fixhub/Fixhub#89]
这个调用报错~~

**Comment by lianguan** [comment]
直接copy，在浏览器地址栏调用？这个是会报错的。

**Comment by shuipf** [comment]
是的~~~那正确的方式是？

**Comment by lianguan** [comment]
![image](https://user-images.githubusercontent.com/15666864/31535789-e7f031d8-b02e-11e7-9eaf-e86b3f772653.png)

**Comment by shuipf** [comment]
谢谢~~~
