### ISSUE TITLE
php artisan app:install 执行最后报错

### ISSUE THREAD

**Issue by busyfree** [Fixhub/Fixhub#92]
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Application key [base64:QFFwlQINYY6/CEmsDhQYhihco//hp2WRGcWf8bSg7oA=] set successfully.
Running database migrations

Migration table created successfully.

                                                           
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Call to undefined method Event::fire()

**Comment by lianguan** [comment]
很可能是js-localization报的错，Event::fire在laravel 5.5不被支持了，但这个应该不影响fixhub的安装。
