### ISSUE TITLE
手动上线成功.WEBHOOK 上线失败

### ISSUE THREAD

**Issue by zuozhehao** [Fixhub/Fixhub#93]
[2017-10-13 17:59:27] production.ERROR: Could not get repository info - fatal: bad object 29c0726d41284042e34860cc9082b3475744b199
 {"exception":"[object] (RuntimeException(code: 0): Could not get repository info - fatal: bad object 29c0726d41284042e34860cc9082b3475744b199
 at /home/xxxx/app/Bus/Jobs/DeployProjectJob.php:187)
[stacktrace]
#0 /home/xxxx/app/Bus/Jobs/DeployProjectJob.php(108): Fixhub\\Bus\\Jobs\\DeployProjectJob->updateRepoInfo()
#1 [internal function]: Fixhub\\Bus\\Jobs\\DeployProjectJob->handle()

**Comment by lianguan** [comment]
Fixed，请使用1.0分支最新提交的版本测一下，记得要重启supervisor。

**Comment by zuozhehao** [comment]
Next Illuminate\\Database\\QueryException: SQLSTATE[HY000] [1045] Access denied for user 'fixhub'@'localhost' (using password: NO) (SQL: select * from `deployments` where `deployments`.`id` = 1 limit 1) in /home/xxxx/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664

换了一台测试机重新拉取,重新安装,手动上线的时候报错了.
为啥数据库是localhost,我明明设置的是一个域名

**Comment by lianguan** [comment]
改了.env，要记得php artisan config:cache

**Comment by zuozhehao** [comment]
这个我有改过了

**Comment by lianguan** [comment]
这个是laravel的标准处理方法，fixhub没有额外的处理。如果方便，把ssh账号发给我，我帮你看看。
