### ISSUE TITLE
这个问题不知道是不是Bug

### ISSUE THREAD

**Issue by shuipf** [Fixhub/Fixhub#99]
![image](https://user-images.githubusercontent.com/2285144/31598112-72a25d04-b211-11e7-82cd-2cf32c404b7d.png)
![image](https://user-images.githubusercontent.com/2285144/31598121-7d53c53a-b211-11e7-8cbe-cc591b1e17c6.png)

预发环境下有1台服务器
正式环境下有2台服务器

上线单，正常情况下，预发环境+正式环境，应该只是更新3个。结果有5个。

![image](https://user-images.githubusercontent.com/2285144/31598150-ad999c1a-b211-11e7-978d-ca5870f078a1.png)

复制的，其他项目上线单是3个，就个别有的会这样

**Comment by lianguan** [comment]
等我想办法复现一下。

**Comment by shuipf** [comment]
感觉你外键弄的太厉害，有啥删条数据都因为完整性约束

**Comment by shuipf** [comment]
早上升级最新版
现在变成这样啦？
![image](https://user-images.githubusercontent.com/2285144/31641519-c754b1fa-b2aa-11e7-9885-ed2b9f60b8dd.png)

**Comment by lianguan** [comment]
@shuipf 有什么变化？

**Comment by shuipf** [comment]
这是昨天同一个项目的，你对比下就知道了
![image](https://user-images.githubusercontent.com/2285144/31641722-3ce6f5da-b2ac-11e7-97e9-63dd35aaf2db.png)

**Comment by lianguan** [comment]
查看下服务器的启用状态。

**Comment by shuipf** [comment]
预发环境 下 一台 有启用
正式环境 下两台 有启用

**Comment by lianguan** [comment]
删除了一个“是否部署代码”，现在只要关注“服务器是否启用”
